"""Questions orales du catalogue, distinctes des références bibliographiques."""

QUESTIONS = {
    "16.1.1": "Donnez-moi la définition d'une série.",
    "16.1.5": "Donnez-moi la définition d'une série convergente.",
    "16.1.9": "Énoncez le critère de convergence d'une série géométrique et précisez sa somme lorsqu'elle converge.",
    "16.1.11": "Que peut-on dire de la nature de deux séries dont les termes ne diffèrent qu'en un nombre fini de rangs ?",
    "16.1.12": "Quelle condition nécessaire le terme général d'une série convergente doit-il vérifier ?",
    "16.1.13": "Que signifie qu'une série diverge grossièrement ?",
    "16.1.15": "Énoncez la propriété de linéarité pour les séries convergentes, avec ses hypothèses.",
    "16.2.1": "À quelle condition sur ses sommes partielles une série à termes positifs converge-t-elle ?",
    "16.2.2": "Énoncez le théorème de comparaison des séries à termes positifs, en précisant ses hypothèses.",
    "16.2.3": "Donnez-moi la définition d'une série absolument convergente.",
    "16.2.4": "Quel lien existe-t-il entre convergence absolue et convergence d'une série ? Précisez les hypothèses.",
    "16.2.7": "Donnez-moi la définition d'une série semi-convergente.",
    "16.2.8": "Énoncez les critères de comparaison des séries par domination et par négligeabilité, avec leurs hypothèses.",
    "16.2.9": "Énoncez le théorème de comparaison par équivalence pour les séries à termes positifs, avec ses hypothèses.",
    "16.2.13": "Énoncez le théorème de comparaison entre une série et une intégrale, avec ses hypothèses.",
    "16.2.14": "Quelle est la nature d'une série géométrique selon sa raison ?",
    "16.2.15": "Quelle est la nature d'une série exponentielle ? Précisez les valeurs du paramètre concernées.",
    "16.2.16": "Donnez-moi la définition d'une série de Riemann.",
    "16.2.17": "Énoncez le critère de convergence des séries de Riemann.",
    "16.2.18": "Énoncez le critère de convergence des séries de Bertrand, en précisant les paramètres.",
    "16.2.20": "Énoncez la règle de Riemann pour les séries à termes positifs, avec ses hypothèses.",
    "16.2.22": "Énoncez la règle de d'Alembert, avec ses hypothèses et les différents cas possibles.",
    "16.3.1": "Donnez-moi la définition d'une série alternée.",
    "16.3.2": "Énoncez le théorème de convergence des séries alternées, avec ses hypothèses.",
    "16.3.5": "Énoncez le critère d'Abel pour les séries, avec ses hypothèses.",
    "16.4.1": "Comment caractérise-t-on la convergence d'une série à termes positifs à l'aide des sommes sur les parties finies ?",
    "16.4.2": "Comment définit-on la somme d'une famille quelconque de termes positifs ?",
    "16.4.3": "Énoncez la propriété de comparaison des sommes de familles positives, avec ses hypothèses.",
    "16.4.4": "À quelle condition une famille de termes positifs est-elle sommable ?",
    "16.4.5": "Que peut-on dire de la sommabilité et de la somme d'une famille finie ?",
    "16.4.6": "Quel lien existe-t-il entre les séries à termes positifs et les familles sommables ?",
    "16.4.9": "Énoncez la propriété d'associativité des sommes de familles positives, avec ses hypothèses.",
    "16.4.13": "Donnez-moi la définition d'une famille sommable de nombres réels ou complexes.",
    "16.4.15": "Que peut-on dire de la sommabilité d'une sous-famille d'une famille sommable ?",
    "16.4.16": "Énoncez le théorème de comparaison pour la sommabilité des familles, avec ses hypothèses.",
    "16.4.17": "Comment caractérise-t-on la sommabilité à l'aide des parties réelle et imaginaire, ou des parties positive et négative ?",
    "16.4.18": "Comment définit-on la somme d'une famille sommable de nombres réels ou complexes ?",
    "16.4.19": "Énoncez la caractérisation de la somme d'une famille sommable à l'aide d'un epsilon et de parties finies.",
    "16.4.20": "Énoncez la propriété de linéarité de la somme des familles sommables, avec ses hypothèses.",
    "16.4.21": "Quel lien existe-t-il entre la sommabilité d'une famille indexée par les entiers naturels et la série associée ?",
    "16.4.22": "Énoncez la propriété d'associativité de la somme des familles sommables, avec ses hypothèses.",
    "16.4.24": "Énoncez le théorème sur le produit de deux familles sommables, avec ses hypothèses.",
    "16.4.25": "Énoncez le théorème sur le produit de Cauchy de deux séries, avec ses hypothèses.",
    "16.5.1": "Donnez-moi la définition de la série exponentielle.",
    "16.5.2": "Énoncez le résultat de convergence de la série exponentielle, en précisant son domaine de validité.",
    "16.5.3": "Quelle relation l'exponentielle vérifie-t-elle pour une somme de deux nombres complexes ?",
    "16.5.5": "Donnez les développements en série de l'exponentielle, du cosinus et du sinus, en précisant leur domaine de validité.",
    "16.6.1": "Énoncez la formule du binôme négatif, avec ses conditions de validité.",
}
